

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String:      ""
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
//  Failed to find providerName in the connection string
// ------------------------------------------------------------------------------------------------

